---
name: Run CI checks
on:
  pull_request_target:
    types: "*"
    branches: "**"

  pull_request_review:
    types: "**"
    branches: "**"

permissions: read-all
jobs:
  trigger_workflows:
      uses: projectceladon/workflows/.github/workflows/trigger_ci.yml@main
      with:
        EVENT: ${{ toJSON(github.event) }}
