---
name: Run CI checks
on:
  pull_request_target:
    types: "*"
    branches: "**"

  pull_request_review:
    types: "**"
    branches: "**"

permissions: read-all
jobs:
  trigger_workflows:
    runs-on: ubuntu-latest
    steps:
      uses: projectceladon/workflows/.github/workflows/trigger_ci.yml@main
      with:
        EVENT: ${{ toJSON(github.event) }}
